import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import NavBar from "@/components/NavBar";
import { getCurrentAdmin } from "@/lib/current-admin";
import "./globals.css";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const admin = await getCurrentAdmin();

  return (
    <html
      lang="th"
      className={`${notoSansThai.variable} ${notoSansThai.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar admin={admin} />
        {children}
      </body>
    </html>
  );
}
